### ISSUE TITLE
Make a pull request in Quasar instead

### ISSUE THREAD

**Issue by scakemyer** [mancuniancol/script.mod-quasar#1]
:p

**Comment by mancuniancol** [comment]
It is not my code. Then, it's not my call. I am just helping someone.

**Comment by mancuniancol** [comment]
It seems that the code comes from this issue in Quasar.

https://github.com/scakemyer/plugin.video.quasar/issues/12

I've tested and it works.

**Comment by scakemyer** [comment]
Just found it too going over older issues, looks good so I'll make the change in plugin.video.quasar :)
